### ISSUE TITLE
Add support for the Java root store

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/trust_stores_observatory#1]
This would require:

* Downloading the latest JRE at http://www.oracle.com/technetwork/java/javase/downloads/index.html
* Parsing the cacerts file in it

**Comment by stefanb** [comment]
Some alternatives to downloading the full JRE/JDK distribution:

* JDK enhancment proposal (JEP): http://openjdk.java.net/jeps/319
* Jira ticket: https://bugs.openjdk.java.net/browse/JDK-8191486
* Latest in Mercurial: http://hg.openjdk.java.net/jdk/jdk/file/tip/src/java.base/share/lib/security/cacerts

**Comment by nabla-c0d3** [comment]
Thanks for the details and I agree that they should be treated separately; the JEP says that "each CA must sign the Oracle Contributor Agreement (OCA), or an equivalent agreement, to grant Oracle the right to open-source their certificates. [...]. Those that do not sign an agreement will not be included at this time", so the content of the stores will be different for sure.

**Comment by nabla-c0d3** [comment]
Implemented in https://github.com/nabla-c0d3/trust_stores_observatory/pull/7
