### ISSUE TITLE
java: add certificates from openjdk 11 (latest release)

### ISSUE THREAD

**Issue by adamdecaf** [nabla-c0d3/trust_stores_observatory#13]
https://github.com/nabla-c0d3/trust_stores_observatory/pull/12 mentioned this project uses Oracle's Java 8. Their newer releases require licensing for commercial use, but OpenJDK is free for projects to use.

**Comment by adamdecaf** [comment]
cc @stefanb

**Comment by stefanb** [comment]
Apparently Oracle hasn't yet publically released Java 11 JRE, only JDK. This is why build is currently failing as Java fetcher picked up older, slightly (in regards to certificate store) different JRE from Java 8. In #12 I adjusted the fetcher to work with that old JRE, but that is not a proper solution.

OpenJDK store should be added, not replacing the Oracle's one.

**Comment by stefanb** [comment]
The CA root certificates in the repository seems to be in:
http://hg.openjdk.java.net/jdk/jdk/file/tip/src/java.base/share/lib/security/cacerts

**Comment by adamdecaf** [comment]
That's master though (Java 12 pre-release). We probably want to grab the
latest 11 tag

http://hg.openjdk.java.net/jdk/jdk/file/76072a077ee1/src/java.base/share/lib/security/cacerts

**Comment by stefanb** [comment]
Or even better: check what is actually being distributed in the downloadable files/installers available at
https://openjdk.java.net/install/

**Comment by stefanb** [comment]
Implemeted fetching of OpenJDK KeyStore (latest from Mercurial repository) in PR #14
