### ISSUE TITLE
iOS 16 certificates missing

### ISSUE THREAD

**Issue by itaybia** [nabla-c0d3/trust_stores_observatory#26]
some certificates from https://support.apple.com/en-us/HT213464 are missing:

1be7abe30686b16348afd1c61b6866a0ea7f4821e67d5e8af937cf8011bc750d: HARICA Client RSA Root CA 2021
77b82cd8644c4305f7acc5cb156b45675004033d51c60c6202a8e0c33467d3a0: Certainly Root R1
6b328085625318aa50d173c98d8bda09d57e27413d114cf787a0f5d06c030cf6: Certum EC-384 CA
9a296a5182d1d451a2e37f439b74daafa267523329f90f9a0d2007c334e23c9a: GLOBALTRUST 2020
657cfe2fa73faa38462571f332a2363a46fce7020951710702cdfbb6eeda3305: certSIGN ROOT CA G2
8dd4b5373cb0de36769c12339280d82746b3aa6cd426e797a31babe4279cf00b: HARICA Client ECC Root CA 2021
88f438dcf8ffd1fa8f429115ffe5f82ae1e06e0c70c375faad717b34a49e7265: NAVER Global Root Certification Authority
69729b8e15a86efc177a57afb7171dfc64add28c2fca8cf1507e34453ccb1470: ISRG Root X2
d95d0e8eda79525bf9beb11b14d2100d3294985f0c62d9fabd9cd999eccb7b1d: HARICA TLS RSA Root CA 2021
fe7696573855773e37a95e7ad4d9cc96c30157c15d31765ba9b15704e1ae78fd: Certum Trusted Root CA
b4585f22e4ac756a4e8612a1361c5d9d031a93fd84febb778fa3068b0fc42dc2: Certainly Root E1
3f99cc474acfce4dfed58794665e478d1547739f2e780f1bb4ca9b133097d401: HARICA TLS ECC Root CA 2021

most can be found here:
https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt

the rest can be found here:
https://repo.harica.gr/rep_dyn.php

**Comment by nabla-c0d3** [comment]
Fixed in https://github.com/nabla-c0d3/trust_stores_observatory/commit/53ddbac31a735d83402c3ee7a7996b05f01bbc1d
