### ISSUE TITLE
cron for generating certificate lists

### ISSUE THREAD

**Issue by adamdecaf** [nabla-c0d3/trust_stores_observatory#6]
What would you think about using `cert-manage` (I've released 0.1.0) to generate observatory yamls from installed CA store instances during the weekly cron?

This would be via dockerfiles like: `openjdk:9-jre` and `ubuntu:latest`. Ideally every stable and latest app/platform could be included. We could install apps (chrome, firefox) into dockerfiles too. 

There should be good enough versions embedded in the observatory yaml now. 

```
$ ./cert-manage list -app java -format observatory | head -n2
platform: Java
version: 1.8.0_152

$ ./cert-manage list -app chrome -format observatory | head -n2
platform: Chrome
version: 63.0.3239.132

$ ./cert-manage list -format observatory | head -n2
platform: Darwin (OSX)
version: 10.13.3
```

https://hub.docker.com/_/ubuntu/
https://hub.docker.com/_/openjdk/

**Comment by adamdecaf** [comment]
> I am wondering if there is an easier way to get the stores than launching a full VM or Docker

Maybe? I'm more interested in being able to extract that from running instances. Parsing all those provider html pages isn't something I want to add into cert-manage.

I'll help to run a bunch of cert-manage things in docker images and we could likely work out a way to contribute the whitelists over into this project. I want to have a bunch of integration tests for cert-manage anyway.

**Comment by nabla-c0d3** [comment]
One thing that's crucial for me and this project, is that the process to extract the stores need to be done automatically every week or so, so it can keep track of all the changes over time (hence my comments above).
A one time, manual export of the stores is not something I would want to add to this repo.

**Comment by adamdecaf** [comment]
Totally agree. I'm thinking of shipping over the yaml output after integration tests ran on a schedule.

**Comment by nabla-c0d3** [comment]
Closing this as it was more of a discussion I think? Using more than Travis CI for refreshing the stores automatically is outside of the scope of this project, at least for now.
